---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by mraof.
--- DateTime: 8/26/19 6:51 PM
---

after = {"beatfox", "aerosoul", "obj", "karacel", "regions", "genders"}

config["species"] = {
    {
        species = "beatfox",
        region = "gen luxson cluster",
        gender = "gen genders",
        generator = "gen beatfox"
    },
    {
        species = "aerosoul",
        region = "gen synalboc",
        gender = "gen genders",
        generator = "gen aerosoul"
    },
    {
        generator = "gen obj"
    }
}
