---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by mraof.
--- DateTime: 8/24/19 2:17 PM
---

config["genders"] = {
    "female",
    "male",
    "demigirl",
    "demiboy",
    "nonbinary",
    "agender",
    "genderqueer",
    "genderfluid",
    "questioning",
    "neutrois",
    "androgyne",
    "bigender",
    "pangender",
    "maverique",
    "unknown",
    "other",
    "questioning"
}
