config["sphinx"] = {
  prefixed = {
    species = "sphinx",
    prefix = true,
    head = {
      size = "gen head size",
      shape = {
        {"rounded", UNCOMMON},
        {"pointed", UNCOMMON},
        {"square", UNCOMMON},
        {"triangular", UNCOMMON},
        {"angular", UNCOMMON},
        {"rectangular", UNCOMMON},
        {"oval", COMMON},
        {"long muzzled", RARE},
        {"short muzzled", RARE},
        {"catlike", RARE},
        {"sloped", VERY_RARE}
      }
    },
    eye = {
      shape = "gen eye shape",
      color = {
        {"light pink", VERY_RARE},
        {"pink", RARE},
        {"dark pink", UNCOMMON},
        {"light red", VERY_RARE},
        {"red", RARE},
        {"dark red", UNCOMMON},
        {"orange", RARE},
        {"light orange", VERY_RARE},
        {"dark orange", UNCOMMON},
        {"yellow", RARE},
        {"light yellow", VERY_RARE},
        {"dark yellow", UNCOMMON},
        {"light chartreuse", VERY_RARE},
        {"chartreuse", RARE},
        {"dark chartreuse", UNCOMMON},
        {"green", RARE},
        {"light green", VERY_RARE},
        {"dark green", UNCOMMON},
        {"blue", RARE},
        {"light blue", VERY_RARE},
        {"dark blue", UNCOMMON},
        {"light indigo", VERY_RARE},
        {"indigo", RARE},
        {"dark indigo", UNCOMMON},
        {"purple", RARE},
        {"light purple", VERY_RARE},
        {"dark purple", UNCOMMON},
        {"white", VERY_RARE},
        {"light gray", VERY_RARE},
        {"mid-light gray", VERY_RARE},
        {"gray", RARE},
        {"mid-dark gray", RARE},
        {"dark gray", UNCOMMON},
        {"black", COMMON},
        {"tan", RARE},
        {"dark tan", UNCOMMON},
        {"light tan", VERY_RARE},
        {"light brown", VERY_RARE},
        {"dark brown", UNCOMMON},
        {"brown", RARE}
      }
    },
    pupil = {
      shape = {
        {"slit", COMMON},
        {"round", UNCOMMON},
        {"heart", RARE},
        {"star", RARE},
        {"sparkle", RARE},
        {"multiple", VERY_RARE}
      }
    },
    teeth = {
      color = "white",
      style = "gen teeth style"
    },
    tongue = {
      color = {
        {"light pink", RARE},
        {"pink", RARE},
        {"dark pink", RARE},
        {"light red", UNCOMMON},
        {"red", COMMON},
        {"dark red", UNCOMMON},
        {"orange", RARE},
        {"light orange", RARE},
        {"dark orange", RARE},
        {"yellow", RARE},
        {"light yellow", RARE},
        {"dark yellow", RARE},
        {"light chartreuse", RARE},
        {"chartreuse", RARE},
        {"dark chartreuse", RARE},
        {"green", COMMON},
        {"light green", UNCOMMON},
        {"dark green", UNCOMMON},
        {"blue", COMMON},
        {"light blue", UNCOMMON},
        {"dark blue", UNCOMMON},
        {"light indigo", RARE},
        {"indigo", RARE},
        {"dark indigo", RARE},
        {"purple", COMMON},
        {"light purple", UNCOMMON},
        {"dark purple", UNCOMMON},
        {"white", COMMON},
        {"light gray", UNCOMMON},
        {"mid-light gray", UNCOMMON},
        {"gray", COMMON},
        {"mid-dark gray", UNCOMMON},
        {"dark gray", UNCOMMON},
        {"black", COMMON},
        {"tan", RARE},
        {"dark tan", RARE},
        {"light tan", RARE},
        {"light brown", RARE},
        {"dark brown", RARE},
        {"brown", COMMON},
        {"gold", COMMON},
        {"dark gold", UNCOMMON},
        {"light gold", UNCOMMON}
      },
      style = {
        {"round", COMMON},
        {"pointed", UNCOMMON},
        {"forked", RARE},
        {"split", VERY_RARE}
      }
    },
    ear = {
      size = "gen ear size",
      type = {
        {"pointed", COMMON},
        {"rounded", UNCOMMON},
        {"lop", RARE},
        {"sideways", RARE},
        {"horns instead of", VERY_RARE}
      }
    },
    weight = "gen weight",
    height = "gen height",
    build = "gen build",
    scale = "gen scale",
    neck = "gen neck",
    shoulders = "gen shoulders",
    chest = "gen chest",
    bust = "gen bust",
    arm = {
      length = "gen arm length",
      size = "gen arm size"
    },
    hand = "gen hand",
    hips = "gen hips",
    leg = {
      length = "gen leg length",
      size = "gen leg size"
    },
    feet = "gen feet",
    tail = {
      length = "gen tail length",
      type = {
        {"tufted", COMMON},
        {"tapered", UNCOMMON},
        {"fluffy", RARE},
        {"devil", RARE},
        {"whip", UNCOMMON},
        {"tendril", RARE},
        {"fin", VERY_RARE},
        {"stinger", VERY_RARE},
        {"spiral", VERY_RARE},
        {"maw", VERY_RARE}
      }
    },
    wing = {
     {{
        type = {
          {"feathery", COMMON},
          {"fin", VERY_RARE},
          {"scaled", VERY_RARE},
          {"seraph", VERY_RARE},
          {"torn", RARE},
          {"tendril", VERY_RARE}
        },
        color = {
          {"light pink", RARE},
          {"pink", VERY_RARE},
          {"dark pink", VERY_RARE},
          {"light red", COMMON},
          {"red", UNCOMMON},
          {"dark red", RARE},
          {"orange", VERY_RARE},
          {"light orange", RARE},
          {"dark orange", VERY_RARE},
          {"yellow", VERY_RARE},
          {"light yellow", RARE},
          {"dark yellow", VERY_RARE},
          {"light chartreuse", RARE},
          {"chartreuse", VERY_RARE},
          {"dark chartreuse", VERY_RARE},
          {"green", UNCOMMON},
          {"light green", COMMON},
          {"dark green", RARE},
          {"blue", UNCOMMON},
          {"light blue", COMMON},
          {"dark blue", RARE},
          {"light indigo", RARE},
          {"indigo", VERY_RARE},
          {"dark indigo", VERY_RARE},
          {"purple", UNCOMMON},
          {"light purple", COMMON},
          {"dark purple", RARE},
          {"white", COMMON},
          {"light gray", COMMON},
          {"mid-light gray", UNCOMMON},
          {"gray", UNCOMMON},
          {"mid-dark gray", UNCOMMON},
          {"dark gray", UNCOMMON},
          {"black", COMMON},
          {"tan", VERY_RARE},
          {"dark tan", VERY_RARE},
          {"light tan", RARE},
          {"light brown", RARE},
          {"dark brown", VERY_RARE},
          {"brown", VERY_RARE},
          {"gold", UNCOMMON},
          {"dark gold", RARE},
          {"light gold", COMMON}
        }
      }, COMMON},
      {{type = "no"}, VERY_RARE}
    },
    blood = {
      color = {
        {"light pink", RARE},
        {"pink", RARE},
        {"dark pink", RARE},
        {"light red", UNCOMMON},
        {"red", COMMON},
        {"dark red", UNCOMMON},
        {"orange", RARE},
        {"light orange", RARE},
        {"dark orange", RARE},
        {"yellow", RARE},
        {"light yellow", RARE},
        {"dark yellow", RARE},
        {"light chartreuse", RARE},
        {"chartreuse", RARE},
        {"dark chartreuse", RARE},
        {"green", COMMON},
        {"light green", UNCOMMON},
        {"dark green", UNCOMMON},
        {"blue", COMMON},
        {"light blue", UNCOMMON},
        {"dark blue", UNCOMMON},
        {"light indigo", RARE},
        {"indigo", RARE},
        {"dark indigo", RARE},
        {"purple", COMMON},
        {"light purple", UNCOMMON},
        {"dark purple", UNCOMMON},
        {"white", COMMON},
        {"light gray", UNCOMMON},
        {"mid-light gray", UNCOMMON},
        {"gray", COMMON},
        {"mid-dark gray", UNCOMMON},
        {"dark gray", UNCOMMON},
        {"black", COMMON},
        {"tan", RARE},
        {"dark tan", RARE},
        {"light tan", RARE},
        {"light brown", RARE},
        {"dark brown", RARE},
        {"brown", COMMON},
        {"gold", COMMON},
        {"dark gold", UNCOMMON},
        {"light gold", UNCOMMON}
      }
    },
    bones = {
      color = "white"
    },
    organ = {
      color = {
{"light pink", RARE},
        {"pink", RARE},
        {"dark pink", RARE},
        {"light red", UNCOMMON},
        {"red", COMMON},
        {"dark red", UNCOMMON},
        {"orange", RARE},
        {"light orange", RARE},
        {"dark orange", RARE},
        {"yellow", RARE},
        {"light yellow", RARE},
        {"dark yellow", RARE},
        {"light chartreuse", RARE},
        {"chartreuse", RARE},
        {"dark chartreuse", RARE},
        {"green", COMMON},
        {"light green", UNCOMMON},
        {"dark green", UNCOMMON},
        {"blue", COMMON},
        {"light blue", UNCOMMON},
        {"dark blue", UNCOMMON},
        {"light indigo", RARE},
        {"indigo", RARE},
        {"dark indigo", RARE},
        {"purple", COMMON},
        {"light purple", UNCOMMON},
        {"dark purple", UNCOMMON},
        {"white", COMMON},
        {"light gray", UNCOMMON},
        {"mid-light gray", UNCOMMON},
        {"gray", COMMON},
        {"mid-dark gray", UNCOMMON},
        {"dark gray", UNCOMMON},
        {"black", COMMON},
        {"tan", RARE},
        {"dark tan", RARE},
        {"light tan", RARE},
        {"light brown", RARE},
        {"dark brown", RARE},
        {"brown", COMMON},
        {"gold", COMMON},
        {"dark gold", UNCOMMON},
        {"light gold", UNCOMMON}
      }
    },
    fur_skin = {
      color = {
        {"light pink", RARE},
        {"pink", RARE},
        {"dark pink", RARE},
        {"light red", UNCOMMON},
        {"red", COMMON},
        {"dark red", UNCOMMON},
        {"orange", RARE},
        {"light orange", RARE},
        {"dark orange", RARE},
        {"yellow", RARE},
        {"light yellow", RARE},
        {"dark yellow", RARE},
        {"light chartreuse", RARE},
        {"chartreuse", RARE},
        {"dark chartreuse", RARE},
        {"green", COMMON},
        {"light green", UNCOMMON},
        {"dark green", UNCOMMON},
        {"blue", COMMON},
        {"light blue", UNCOMMON},
        {"dark blue", UNCOMMON},
        {"light indigo", RARE},
        {"indigo", RARE},
        {"dark indigo", RARE},
        {"purple", COMMON},
        {"light purple", UNCOMMON},
        {"dark purple", UNCOMMON},
        {"white", COMMON},
        {"light gray", UNCOMMON},
        {"mid-light gray", UNCOMMON},
        {"gray", COMMON},
        {"mid-dark gray", UNCOMMON},
        {"dark gray", UNCOMMON},
        {"black", COMMON},
        {"tan", RARE},
        {"dark tan", RARE},
        {"light tan", RARE},
        {"light brown", RARE},
        {"dark brown", RARE},
        {"brown", COMMON},
        {"gold", COMMON},
        {"dark gold", UNCOMMON},
        {"light gold", UNCOMMON}
      },
      type = {
        {"fur", COMMON},
        {"cloth", RARE},
        {"scales", RARE},
        {"porcelain", RARE},
        {"glitter", RARE},
        {"meat", RARE},
        {"plush", RARE},
        {"plastic", RARE},
        {"latex", RARE},
        {"skin", RARE}
      }
    },
    accessory = {
      {{
          type = {
          {"fluff", COMMON},
          {"a mane", COMMON},
          {"jewelry", COMMON},
          {"a halo", UNCOMMON},
          {"halos", RARE},
          {"flowers", RARE},
          {"slime", RARE},
          {"fire", RARE},
          {"ruffles", RARE},
          {"bows", RARE},
          {"a bow", UNCOMMON},
          {"collar", UNCOMMON},
          {"horns", RARE},
          {"tendrils", RARE},
          {"wings", VERY_RARE},
          {"spikes", RARE}
        }
      },RARE},
      {"", COMMON}
    },
    pattern = {
      type = {
        {"glitter", COMMON},
        {"fur", COMMON},
        {"cloth", COMMON},
        {"scales", UNCOMMON},
        {"porcelain", UNCOMMON},
        {"glitter", UNCOMMON},
        {"meat", UNCOMMON},
        {"plush", UNCOMMON},
        {"plastic", UNCOMMON},
        {"latex", UNCOMMON},
        {"eyes", UNCOMMON},
        {"sweater", UNCOMMON},
        {"geometric", UNCOMMON},
        {"dotted", UNCOMMON},
        {"pop", UNCOMMON},
        {"spotted", UNCOMMON},
        {"acrylic", UNCOMMON},
        {"stripe", UNCOMMON},
        {"web", UNCOMMON},
        {"antique", UNCOMMON},
        {"square", UNCOMMON},
        {"diamond", UNCOMMON},
        {"chevron", UNCOMMON},
        {"grainy", UNCOMMON},
        {"noise", UNCOMMON},
        {"scratchy", UNCOMMON},
        {"grunge", UNCOMMON},
        {"speckled", UNCOMMON},
        {"floral", UNCOMMON},
        {"dainty", UNCOMMON},
        {"cute", UNCOMMON},
        {"cyber", UNCOMMON},
        {"regal", COMMON},
        {"funky", UNCOMMON},
        {"quilted", UNCOMMON},
        {"bloody", UNCOMMON},
        {"splattered", UNCOMMON},
        {"batik", UNCOMMON},
        {"ombre", UNCOMMON},
        {"chalkboard", UNCOMMON},
        {"starry", UNCOMMON},
        {"paper", UNCOMMON},
        {"graphic", UNCOMMON},
        {"marble", COMMON},
        {"watercolor", UNCOMMON},
        {"dirty", UNCOMMON},
        {"elegant", UNCOMMON},
        {"wrinkly", UNCOMMON},
        {"gilded", COMMON},
        {"metallic", COMMON},
        {"shiny", COMMON},
        {"glamorous", UNCOMMON},
        {"glitzy", COMMON},
        {"hieroglyph", COMMON},
        {"runes", COMMON},
        {"ancient", COMMON},
        {"honeycomb", UNCOMMON},
        {"luxury", COMMON},
        {"iridescent", UNCOMMON},
        {"swirl", COMMON},
        {"map", UNCOMMON},
        {"galaxy", COMMON},
        {"space", UNCOMMON},
        {"grid", UNCOMMON},
        {"scribble", UNCOMMON},
        {"nautical", UNCOMMON},
        {"static", UNCOMMON},
        {"patchwork", UNCOMMON},
        {"carnival", UNCOMMON},
        {"kiddy", UNCOMMON},
        {"gothic", UNCOMMON},
        {"retro", UNCOMMON},
        {"foil", COMMON},
        {"shimmer", COMMON},
        {"velvet", COMMON},
        {"vintage", UNCOMMON},
        {"waveform", UNCOMMON},
        {"line", UNCOMMON},
        {"wave", UNCOMMON},
        {"wood", UNCOMMON}
      },
      color = {
{"light pink", RARE},
        {"pink", RARE},
        {"dark pink", RARE},
        {"light red", UNCOMMON},
        {"red", COMMON},
        {"dark red", UNCOMMON},
        {"orange", RARE},
        {"light orange", RARE},
        {"dark orange", RARE},
        {"yellow", RARE},
        {"light yellow", RARE},
        {"dark yellow", RARE},
        {"light chartreuse", RARE},
        {"chartreuse", RARE},
        {"dark chartreuse", RARE},
        {"green", COMMON},
        {"light green", UNCOMMON},
        {"dark green", UNCOMMON},
        {"blue", COMMON},
        {"light blue", UNCOMMON},
        {"dark blue", UNCOMMON},
        {"light indigo", RARE},
        {"indigo", RARE},
        {"dark indigo", RARE},
        {"purple", COMMON},
        {"light purple", UNCOMMON},
        {"dark purple", UNCOMMON},
        {"white", COMMON},
        {"light gray", UNCOMMON},
        {"mid-light gray", UNCOMMON},
        {"gray", COMMON},
        {"mid-dark gray", UNCOMMON},
        {"dark gray", UNCOMMON},
        {"black", COMMON},
        {"tan", RARE},
        {"dark tan", RARE},
        {"light tan", RARE},
        {"light brown", RARE},
        {"dark brown", RARE},
        {"brown", COMMON},
        {"gold", COMMON},
        {"dark gold", UNCOMMON},
        {"light gold", UNCOMMON}
      }
    },
    district = {
        {"Hospital", COMMON},
        {"Therapy", COMMON},
        {"Violence", COMMON},
        {"Disaster", COMMON},
        {"Accident", COMMON},
        {"Nature", COMMON},
        {"Research", COMMON}
    },
    classification = {
        {"demon", EXTREMELY_RARE},
        {"angel", EXTREMELY_RARE},
        {"fae", COMMON},
        {"cryptid", EXTREMELY_RARE},
        {"ghost", EXTREMELY_RARE},
        {"monster", EXTREMELY_RARE},
        {"synth", EXTREMELY_RARE}
    },
    power = {
      strength = {
        {"godlike", EXTREMELY_RARE},
        {"very powerful", VERY_RARE},
        {"powerful", UNCOMMON},
        {"average", COMMON},
        {"weak", UNCOMMON},
        {"very weak", VERY_RARE},
        {"minimal", EXTREMELY_RARE}
      },
      type = {
        {"typical", COMMON},
        {"atypical", UNCOMMON},
        {"bizarre", RARE}
      }
    }
  }
}
